# Generated by Django 6.0.7 on 2026-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('supplier_code', models.CharField(max_length=20)),
                ('quoted_base', models.IntegerField()),
                ('quoted_tax', models.IntegerField()),
                ('quoted_currency', models.CharField(max_length=3)),
                ('snapshot_base', models.IntegerField(blank=True, null=True)),
                ('snapshot_tax', models.IntegerField(blank=True, null=True)),
                ('snapshot_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('invoiced_base', models.IntegerField(blank=True, null=True)),
                ('invoiced_tax', models.IntegerField(blank=True, null=True)),
                ('invoiced_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('status', models.CharField(db_index=True, default='CREATED', max_length=30)),
                ('leakage_amount', models.IntegerField(default=0)),
                ('discrepancy_breakdown', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
