events {
    worker_connections 1024;
}

http {
    upstream react_frontend { server react-admin:80; }
    upstream fastify_backend { server fastify-server:3000; }
    upstream django_backend { server django-web:8000; }

    server {
        listen 80;

        # serve react to non api endpoints
        location / {
            proxy_pass http://react_frontend;
            proxy_set_header Host $host;
        }

        # fastify routes
        location /api/bookings {
            proxy_pass http://fastify_backend;
            proxy_set_header Host $host;
        }
        location /api/invoices {
            proxy_pass http://fastify_backend;
            proxy_set_header Host $host;
        }
        location /api/snapshots {
            proxy_pass http://fastify_backend;
            proxy_set_header Host $host;
        }

        # django routes
        location /api/audits {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
        }
        location /api/anomalies {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
        }
    }
}
