# Generated by Django 6.0.7 on 2026-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20, unique=True)),
                ('total_audits', models.IntegerField(default=0)),
                ('failed_audits', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
